spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: root
    password: root
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000


app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 30m